[Autologin]


[Theme]
Current=silent

[General]
CursorTheme=future-dark-cursors
CursorSize=24
InputMethod=qtvirtualkeyboard
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components,QT_IM_MODULE=qtvirtualkeyboard,CURSOR_THEME=future-dark-cursors,CURSOR_SIZE=24
